### PR TITLE
Fcc hotfix

### PR DESCRIPTION
**Pull request by hazeydreams**
This should fix the issues we were having with the FCC.

### CODE REVIEW

**Comment by hazeydreams** [comment]
@reeganm @kosikhar Can you assign some people to look over this for mistakes, not sure who to add. After this merge I'll move this board into the electrical repo

**Comment by kosikhar** [comment]
Ill look over it tomorrow.

**Comment by hazeydreams** [comment]
Awesome thanks

**Comment by reeganm** [comment]
I'll look at it tonight

**Comment by reeganm** [comment]
My main concern was the power mosfets, checked them and they are good. I hate rs 232 cables, Added mike as a reviewer to check those.
Mike can you check those? Dalin might need to give you the datasheet

**Comment by reeganm** [comment]
Just remembered. Did you change the rj11 part?

**Comment by hazeydreams** [comment]
Did we change the way power's coming in?

**Comment by reeganm** [comment]
No that eagle part is just messed up. I'll fix it tomorrow

**Comment by hazeydreams** [comment]
I'm confused, they worked before

**Comment by hazeydreams** [comment]
but okay cool

**Comment by hazeydreams** [comment]
Mike, the rs232 for the mass flow meter is pinned out under the assumtion we are buying a straight pass through cable (no crossovers). The part it's self seems to have flipped pin numbers.

**Comment by reeganm** [comment]
The pin out on the schematic doesn't match the pinout of the eagle foot
print. (Pins 2345 don't match up). I'll put the fixed one in and change the
schematic so that the board pinout remains the same but they are consistent.

**Pull request merged**
